# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CupertinoInstantAlert' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
  # Pods for CupertinoInstantAlert

	pod 'GoogleMaps'
  	pod 'GooglePlaces'
	
   pod 'Firebase/Core'
	pod ‘Firebase’
     pod 'Firebase/Database'

    pod ’SwiftyJSON’
	pod ‘Alamofire’
  target 'CupertinoInstantAlertTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CupertinoInstantAlertUITests' do
    inherit! :search_paths
    # Pods for testing
  end

 
end
